export const terms = [
  {
    name: "Search Google",
    link: "https://www.google.com/search?q=",
    logo: "Logos/googleSearchLogo.webp",
  },
  {
    name: "Ajio",
    link: "https://www.ajio.com",
    logo: "Logos/ajioLogo.webp",
    count: 0,
  },
  {
    name: "Amazon",
    link: "https://www.amazon.in",
    logo: "Logos/amazonLogo.webp",
    count: 0,
  },
  {
    name: "Ask Senior",
    link: "https://asksenior.in",
    logo: "Logos/askSeniorLogo.webp",
    count: 0,
  },
  {
    name: "Behance",
    link: "https://www.behance.net",
    logo: "Logos/behanceLogo.webp",
    count: 0,
  },
  {
    name: "Canva",
    link: "https://www.canva.com",
    logo: "Logos/canvaLogo.webp",
    count: 0,
  },
  {
    name: "ChatGPT",
    link: "https://chatgpt.com",
    logo: "Logos/chatgptLogo.webp",
    count: 0,
  },
  {
    name: "Codeforces",
    link: "https://codeforces.com",
    logo: "Logos/codeforcesLogo.webp",
    count: 0,
  },
  {
    name: "Coolors",
    link: "https://coolors.co",
    logo: "Logos/coolorsLogo.webp",
    count: 0,
  },
  {
    name: "Cosmos",
    link: "https://www.cosmos.so",
    logo: "Logos/cosmosLogo.webp",
    count: 0,
  },
  {
    name: "Fitgirl Repacks",
    link: "https://fitgirl-repacks.site",
    logo: "Logos/fitgirlsLogo.webp",
    count: 0,
  },
  {
    name: "Flipkart",
    link: "https://www.flipkart.com",
    logo: "Logos/flipkartLogo.webp",
    count: 0,
  },
  {
    name: "FMHY",
    link: "https://fmhy.net",
    logo: "Logos/fmhyLogo.webp",
    count: 0,
  },
  {
    name: "Gemini",
    link: "https://gemini.google.com",
    logo: "Logos/geminiLogo.webp",
    count: 0,
  },
  {
    name: "GitHub",
    link: "https://github.com",
    logo: "Logos/githubLogo.svg",
    count: 0,
  },
  {
    name: "Gmail",
    link: "https://mail.google.com",
    logo: "Logos/gmailLogo.webp",
    count: 0,
  },
  {
    name: "Godly",
    link: "https://godly.website",
    logo: "Logos/godlyLogo.webp",
    count: 0,
  },
  {
    name: "Google Calendar",
    link: "https://calendar.google.com",
    logo: "Logos/calendarLogo.webp",
    count: 0,
  },
  {
    name: "Google Docs",
    link: "https://docs.google.com",
    logo: "Logos/docsLogo.webp",
    count: 0,
  },
  {
    name: "Google Drive",
    link: "https://drive.google.com",
    logo: "Logos/driveLogo.webp",
    count: 0,
  },
  {
    name: "Google Fonts",
    link: "https://fonts.google.com",
    logo: "Logos/fontsLogo.webp",
    count: 0,
  },
  {
    name: "Google Keep",
    link: "https://keep.google.com",
    logo: "Logos/keepLogo.webp",
    count: 0,
  },
  {
    name: "HackerRank",
    link: "https://www.hackerrank.com",
    logo: "Logos/hackerrankLogo.webp",
    count: 0,
  },
  {
    name: "Instagram",
    link: "https://www.instagram.com",
    logo: "Logos/instagramLogo.webp",
    count: 0,
  },
  {
    name: "LinkedIn",
    link: "https://www.linkedin.com",
    logo: "Logos/linkedinLogo.webp",
    count: 0,
  },
  {
    name: "Monochrome",
    link: "https://monochrome.samidy.com",
    logo: "Logos/monochromeLogo.webp",
    count: 0,
  },
  {
    name: "Myntra",
    link: "https://www.myntra.com",
    logo: "Logos/myntraLogo.webp",
    count: 0,
  },
  {
    name: "Pinterest",
    link: "https://www.pinterest.com",
    logo: "Logos/pinterestLogo.webp",
    count: 0,
  },
  {
    name: "React Bits",
    link: "https://www.reactbits.dev",
    logo: "Logos/reactbitsLogo.webp",
    count: 0,
  },
  {
    name: "Reddit",
    link: "https://www.reddit.com",
    logo: "Logos/redditLogo.webp",
    count: 0,
  },
  {
    name: "Sketchfab",
    link: "https://sketchfab.com",
    logo: "Logos/sketchfabLogo.webp",
    count: 0,
  },
  {
    name: "Spotify",
    link: "https://open.spotify.com",
    logo: "Logos/spotifyLogo.webp",
    count: 0,
  },
  {
    name: "Tailwind CSS",
    link: "https://tailwindcss.com",
    logo: "Logos/tailwindLogo.webp",
    count: 0,
  },
  {
    name: "Telegram Web",
    link: "https://web.telegram.org",
    logo: "Logos/telegramLogo.webp",
    count: 0,
  },
  {
    name: "The Odin Project",
    link: "https://www.theodinproject.com",
    logo: "Logos/odinLogo.webp",
    count: 0,
  },
  {
    name: "Twitch",
    link: "https://www.twitch.tv",
    logo: "Logos/twitchLogo.avif",
    count: 0,
  },
  {
    name: "Twitter",
    link: "https://x.com",
    logo: "Logos/twitterLogo.webp",
    count: 0,
  },
  {
    name: "YouTube",
    link: "https://www.youtube.com",
    logo: "Logos/youtubeLogo.webp",
    count: 0,
  },
  {
    name: "Scientific Calculator",
    link: "https://www.desmos.com/scientific",
    logo: "Logos/desmosLogo.webp",
  },
  {
    name: "Overleaf [Latex]",
    link: "https://www.overleaf.com/project",
    logo: "Logos/overleafLogo.webp",
  },
  {
    name: "Linear Algebra Submission",
    link: "https://docs.google.com/forms/d/e/1FAIpQLSf7lMJ5XdxgfaTV5e3s2MW14KU3HrFORAAlgEpVAt8s12kq1A/viewform",
    logo: "Logos/assignmentLogo.webp",
  },
  {
    name: "Freesound",
    link: "https://freesound.org/",
    logo: "Logos/FreesoundLogo.webp",
  },
];
